version: "3.2"

services:
  sliced:
    image: "samouraiwallet/dojo-bitcoind:${DOJO_SLICED_VERSION_TAG}"
    container_name: sliced
    build:
      context: ./bitcoin
    env_file:
      - ./.env
      - ./conf/docker-common.conf
      - ./conf/docker-bitcoind.conf
    restart: on-failure
    command: "/wait-for-it.sh tor:9050 --timeout=360 --strict -- /restart.sh"
    expose:
      - "40010"
      - "28256"
      - "9501"
      - "9502"
    volumes:
      - data-bitcoind:/home/slice/.slice
      - data-tor:/var/lib/tor
    depends_on:
      - db
      - tor
    networks:
      dojonet:
        ipv4_address: 172.28.1.5

  node:
    depends_on:
      - sliced

volumes:
  data-bitcoind:
